[package]
name = "abi-gen"
version = "0.1.0"
authors = ["Robin Freyler <robin.freyler@gmail.com>"]
edition = "2018"

[[bin]]
name = "abi_gen"
path = "main.rs"

[dependencies]
contract = { path = ".." }
